name: Check Conda Envs

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      envs:
        description: 'Regex for envs'     
        required: false
        default: 'envs/'

jobs:
  check_conda_envs:
    name: Check Conda Envs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Check Conda Envs
        uses: Ulthran/conda_env_check@v0
        with:
          envs: "envs/"
